# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Api tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  deploy-presentation:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install deps
      run: npm ci
    
    - name: Run tests
      run: npm test
      continue-on-error: true

    - name: Run coverage
      run: npm test:coverage
      continue-on-error: true

    - name: Upload report
      uses: actions/checkout@v3
      with:
          name: report
          if-no-files-found: error
          path: ./jest-html-report

    - name: Upload coverage
      uses: actions/checkout@v3
      with:
          name: coverage
          if-no-files-found: error
          path: ./coverage

    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

   - name: Generate a Remark Presentation
      steps:
   - id: generate-presentation
      uses: rreichel3/remarkable-action